### ISSUE TITLE
[var] has no method 'equals'

### ISSUE THREAD

**Issue by amitkeret** [jedmao/eclint#27]
It seems there's an error when trying to get BOM.
As far as I can see, this might be a problem in linez module, or the way it's implemented here.

I've got a js file that starts with `jQuery.extend({`
and another php file starting with `<?php`

This is the output I get:

    $ ./node_modules/.bin/eclint fix file.js
    Unhandled rejection TypeError: Object jQu has no method 'equals'
    
    $ ./node_modules/.bin/eclint file.php
    Unhandled rejection TypeError: Object <?p has no method 'equals'

Here's the backtrace for both:

    at detectCharset (/node_modules/eclint/node_modules/linez/js/linez.js:35:41)
    at linez (/node_modules/eclint/node_modules/linez/js/linez.js:19:19)
    at /node_modules/eclint/js/eclint.js:114:27
    at tryCatcher (/node_modules/eclint/node_modules/editorconfig/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/node_modules/eclint/node_modules/editorconfig/node_modules/bluebird/js/main/promise.js:454:31)
    at Promise._settlePromiseAt (/node_modules/eclint/node_modules/editorconfig/node_modules/bluebird/js/main/promise.js:530:18)
    at Async._drainQueue (/node_modules/eclint/node_modules/editorconfig/node_modules/bluebird/js/main/async.js:182:12)
    at Async._drainQueues (/node_modules/eclint/node_modules/editorconfig/node_modules/bluebird/js/main/async.js:187:10)
    at Async.drainQueues (/node_modules/eclint/node_modules/editorconfig/node_modules/bluebird/js/main/async.js:15:14)
    at process._tickCallback (node.js:415:13)

**Comment by bradlord** [comment]
I ran into this today, and the solution was to upgrade to a later version of Node. Linez relies on the `Buffer` object's `equals()` method, which seems to have been added in Node v0.11.13.

**Comment by jedmao** [comment]
Thank you @bradlord!
